apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: telepresence-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telepresence-cleaner
subjects:
  - kind: ServiceAccount
    name: telepresence-cleaner
    namespace: default
