apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: telepresence-cleaner
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list"]
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs: ["get", "delete", "list"]
